server:
  port: 8989
spring:
  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/yulag_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: localhost
    port: 2399

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 七牛云配置
myoss:
  xxaccessKey: your-access-key
  xxsecretKey: your-secret-key
  xxbucket: your-bucket
